# Front-End: Node.js
frontend:
  image: node:14
  working_dir: /usr/src/app
  volumes:
    - ./frontend:/usr/src/app
  command: sh -c "npm install && npm run start"
  ports:
    - "3000:3000"
  depends_on:
    - backend
  networks:
    - app-network

# Back-End: Python Flask API
backend:
  image: python:3.9
  working_dir: /usr/src/app
  volumes:
    - ./backend:/usr/src/app
  command: sh -c "pip install -r requirements.txt && flask run --host=0.0.0.0"
  environment:
    - FLASK_ENV=development
    - DATABASE_URL=postgresql://postgres_user:postgres_password@db:5432/mydatabase
  ports:
    - "5000:5000"
  depends_on:
    - db
  networks:
    - app-network

# Database: PostgreSQL
db:
  image: postgres:13
  volumes:
    - db_data:/var/lib/postgresql/data
  environment:
    POSTGRES_DB: mydatabase
    POSTGRES_USER: postgres_user
    POSTGRES_PASSWORD: postgres_password
  ports:
    - "5432:5432"
  networks:
    - app-network

# Persistent Volume for Database
volumes:
  db_data:

# Shared Network for All Services
networks:
  app-network:
